CREATE OR REPLACE PROCEDURE PRC_SINC_MOV_PRODUTO AS

   -----------------------DATAS DE ATUALIZACAO
   vDATA_MOV_INCREMENTAL DATE := TRUNC(SYSDATE) - 90;
   --vDATA_MOV_INCREMENTAL DATE := TO_DATE('01/01/2014', 'DD/MM/YYYY'); 

   -----------------------BENEFICIO FISCAL
   vALIQ_ICMS_ES_BENEFICIO NUMBER := 0.011385;
   vDT_INICIO_BENEFICIO_ES DATE := TO_DATE('01/09/2023', 'DD/MM/YYYY'); 

BEGIN
FOR r IN (
 
 WITH 
   -----------------------CFOP DE ENTRADA
  vENT_BONIFICADA         AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1910, 2910, 1911)),
  vENT_CONSERTO           AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1915, 1916, 2915, 2916)),
  vENT_DEMONSTRACAO       AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1912, 1913, 2912, 2913)),
  vENT_DEVOLUCAO          AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1202, 1411, 2202, 2411)),
  vENT_FAT_ENTREGA_FUTURA AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1922, 2922)),
  vENT_COMPRA             AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1101, 1102, 1403, 2102, 2401, 2403)),
  vENT_CONSIGNADO         AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1917, 1918, 2917, 2918)),
  vENT_COMPRA_CONSIGNADO  AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1113, 2113, 1114, 2114)),
  vENT_REM_CONTA_ORDEM    AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1923, 2923)),
  vENT_REM_ENTREGA_FUTURA AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1116, 1117, 2116, 2117)),
  vENT_SIMPLES_REMESSA    AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1908, 1949, 2949)),
  vENT_TRANSFERENCIA      AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1152, 1409, 2152, 2409)),
  vENT_COMPRA_TRIANGULAR  AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (1118,1119, 1121, 2118, 2119, 2121)),

   -----------------------CFOP DE SAIDA
  vSAID_BONIFICADA         AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5910, 6910)),
  vSAID_CONSERTO           AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5915, 5916, 6915, 6916)),
  vSAID_DEMONSTRACAO       AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5912, 6912)),
  vSAID_DESCONSIDERAR      AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5904, 5908, 5929)),
  vSAID_DEVOLUCAO          AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5202, 5209, 5411, 6202, 6411)),
  vSAID_DEV_CONSIGNADO     AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5918, 5919, 6918, 6919)),
  vSAID_FAT_CONTA_ORDEM    AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5119, 6119)),
  vSAID_FAT_ENTREGA_FUTURA AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5922, 6922)),
  vSAID_PERDA_MERCADORIA   AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5927)),
  vSAID_REM_CONTA_ORDEM    AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5923, 6923)),
  vSAID_REM_ENTREGA_FUTURA AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5117, 6117)),
  vSAID_SIMPLES_REMESSA    AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5909, 6909, 5949, 6949)),
  vSAID_TRANSFERENCIA      AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5152, 5409, 6152, 6409)),
  vSAID_VENDA              AS (SELECT CODFISCAL FROM PCCFO F WHERE F.CODFISCAL IN (5115, 6115, 5102, 5109, 5403, 5405, 6102, 6108, 6403, 5120, 6120)),


 MOV_SAIDATV9 AS
  (SELECT M.NUMTRANSVENDA,
          M.NUMTRANSITEM AS NUMTRANSITEM_SAIDATV9,
          M.CODPROD,
          M.CUSTOCONT AS CUSTOCONT_SAIDATV9
     FROM PCMOV M
    WHERE M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_DEMONSTRACAO)
      AND M.STATUS IN ('A' ,'AB')),
  
  CUSTO_TV9 AS
  (SELECT M.NUMTRANSITEM AS NUMTRANSITEM_ENTTV9,
          T.CUSTOCONT_SAIDATV9
     FROM PCMOV M
     LEFT JOIN MOV_SAIDATV9 T ON M.NUMTRANSDEV = T.NUMTRANSVENDA AND M.CODPROD = T.CODPROD
    WHERE M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_DEMONSTRACAO)
      AND M.STATUS IN ('A', 'AB')),
     
      ENTRADAS AS
     (SELECT M.NUMTRANSITEM,
             'E' AS MOVIMENTO,
             (CASE
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_BONIFICADA) THEN 'ENTRADA BONIFICADA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_CONSERTO) THEN 'ENTRADA CONSERTO'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_DEMONSTRACAO) THEN 'ENTRADA DEMONSTRACAO'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_DEVOLUCAO) THEN 'ENTRADA DEVOLUCAO'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_FAT_ENTREGA_FUTURA) THEN 'ENTRADA FAT ENTREGA FUTURA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_COMPRA) THEN 'ENTRADA COMPRA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_CONSIGNADO) THEN 'ENTRADA CONSIGNADO'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_COMPRA_CONSIGNADO) THEN 'ENTRADA COMPRA CONSIGNADO'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_REM_CONTA_ORDEM) THEN 'ENTRADA REM CONTA E ORDEM'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_REM_ENTREGA_FUTURA) THEN 'ENTRADA REM ENTREGA FUTURA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_SIMPLES_REMESSA) THEN 'ENTRADA SIMPLES REMESSA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_TRANSFERENCIA) THEN 'ENTRADA TRANSFERENCIA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_COMPRA_TRIANGULAR) THEN 'ENTRADA COMPRA TRIANGULAR'
               ELSE 'ENTRADA NAO INFORMADA'
             END) TIPOMOV,
             NVL(E.CODFILIALNF, E.CODFILIAL) CODFILIAL,
             M.NUMTRANSENT NUMTRANSACAO,
             (CASE WHEN NVL(E.NUMTRANSVENDAORIG,0) <> 0 THEN 'S' ELSE 'N' END) TEMVENDAORIG,
             '' CODCOB,
             0 PARCELAS,
             NVL(E.PRAZO,0) PRAZO,
             NVL(M.CODUSUR,0) CODUSUR,
             (CASE WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_DEVOLUCAO) THEN 0 ELSE E.CODFORNEC END) CODFORNEC,
             (CASE WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vENT_DEVOLUCAO) THEN E.CODFORNEC ELSE 0 END) CODCLI,
             M.NUMNOTA,
             M.DTMOV DATA,
             M.CODPROD,
             M.QTCONT QT,
             (CASE
               WHEN E.TIPODESCARGA IN ('6', '8', 'C', 'T') THEN ROUND(NVL(M.CUSTOFINEST, 0) * M.QTCONT,4)
               ELSE ROUND(NVL(M.CUSTOFIN, 0),4)
             END) CUSTOFINANCEIRO,
             ROUND(NVL(M.CUSTOREP, 0) * M.QTCONT,4) CUSTOREPOSICAO,
             ROUND(NVL(M.CUSTOCONT, 0) * M.QTCONT,4) CUSTOCONTABIL,
             (CASE
               WHEN E.TIPODESCARGA IN ('6', '8', 'C', 'T') THEN ROUND(M.QTCONT * (M.PUNITCONT + NVL(M.VLFRETE, 0) + NVL(M.VLOUTROS, 0)), 2)
               WHEN E.TIPODESCARGA IN ('N', 'F', 'I') THEN ROUND((M.QTCONT * M.PUNITCONT),2)
               ELSE ROUND(M.QTCONT * (M.PUNITCONT + NVL(M.VLIPI, 0) + NVL(M.ST, 0) + NVL(M.VLFRETE, 0) + NVL(M.VLOUTRASDESP, 0) - NVL(M.VLDESCONTO, 0) - NVL(M.VLSUFRAMA, 0)),2)
             END) VLCONTABIL,
             ROUND(M.PUNITCONT,4) PUNIT,
             ROUND(M.PTABELA,4) PTABELA,
             (CASE
               WHEN E.TIPODESCARGA IN ('6', '8', 'C', 'T') THEN ROUND(M.QTCONT * (M.PUNITCONT + NVL(E.VLDESCONTO, 0) - NVL(M.VLFRETE, 0) - NVL(M.VLOUTRASDESP, 0) - NVL(M.VLIPI, 0) - NVL(M.ST, 0)), 2)
               WHEN E.TIPODESCARGA IN ('N', 'F', 'I') THEN ROUND(M.QTCONT * (M.PUNITCONT + NVL(M.VLDESCONTO, 0) - NVL(M.VLFRETE, 0) - NVL(M.VLOUTRASDESP, 0) - NVL(M.ST, 0)),2)
               ELSE M.QTCONT * M.PUNITCONT
             END) VLPRODUTO,
             CASE
               WHEN E.TIPODESCARGA IN ('6', '8', 'C', 'T') THEN ROUND(M.QTCONT * NVL(E.VLDESCONTO, 0), 2)
               ELSE (M.QTCONT * NVL(M.VLDESCONTO, 0))
             END VLDESCONTO,
             (CASE
               WHEN LENGTH(M.SITTRIBUT) = 1 THEN LPAD(M.SITTRIBUT, 2, '0')
               ELSE M.SITTRIBUT
             END) CST_ICMS,
             M.CODFISCAL CFOP,
             (CASE
               WHEN E.TIPODESCARGA IN ('6', '8', 'C', 'T') THEN ROUND(M.QTCONT * (NVL(M.BASEICMS, 0) + NVL(MC.VLBASEFRETE, 0) + NVL(MC.VLBASEOUTROS, 0)), 2)
               ELSE ROUND(M.QTCONT * NVL(M.BASEICMS, 0), 2)
             END) VLBASEICMS,
             ROUND((NVL(M.PERCICM, 0) / 100),4) PERCICMS,
             (CASE
               WHEN NVL(M.GERAICMSLIVROFISCAL, 'S') = 'N' THEN 0
               WHEN E.TIPODESCARGA IN ('6', '8', 'C', 'T') THEN ROUND(M.QTCONT * (NVL(M.BASEICMS, 0) + NVL(MC.VLBASEFRETE, 0) + NVL(MC.VLBASEOUTROS, 0)) * NVL(M.PERCICM, 0) / 100, 2)
               ELSE ROUND(M.QTCONT * NVL(MC.VLICMS, (NVL(M.BASEICMS, 0) * NVL(M.PERCICM, 0) / 100)),2)
             END) VLICMS,
             0 VLICMSBENEFICIO,
             ROUND(M.QTCONT * NVL(M.ST, 0),4) VLST,
             ROUND(M.QTCONT * NVL(M.VLDESPADICIONAL, 0),4) VLSTGUIA,
             ROUND((NVL(M.PERCIPI, 0) / 100),4) PERCIPI,
             ROUND(M.QTCONT * NVL(M.VLIPI, 0), 2) VLIPI,
             (CASE
               WHEN LENGTH(M.CODSITTRIBPISCOFINS) = 1 THEN LPAD(TO_CHAR(M.CODSITTRIBPISCOFINS), 2, '0')
               ELSE TO_CHAR(M.CODSITTRIBPISCOFINS)
             END) CST_PISCOFINS,
             ROUND(M.QTCONT * NVL(M.VLBASEPISCOFINS, 0), 2) VLBASEPISCOFINS,
             ROUND((M.PERPIS / 100),4) PERCPIS,
             ROUND((M.PERCOFINS / 100),4) PERCCOFINS,
             ROUND(M.QTCONT * NVL(M.VLCREDPIS, 0), 2) VLPIS,
             ROUND(M.QTCONT * NVL(M.VLCREDCOFINS, 0), 2) VLCOFINS,
             ROUND((M.QTCONT * NVL(M.VLFRETE, 0)),4) VLFRETE,
             ROUND(M.QTCONT * NVL(M.VLOUTRASDESP, 0),4) VLOUTRASDESP,
             (ROUND(NVL(M.QTCONT, 0) * NVL(MC.VLICMSPARTREM, 0), 2) + ROUND(NVL(M.QTCONT, 0) * NVL(MC.VLICMSPARTDEST, 0), 2) + ROUND(NVL(M.QTCONT, 0) * NVL(MC.VLFCPPART, 0), 2)) VLICMSDIFAL,
             M.DTCANCEL
        FROM PCNFENT E
        JOIN PCMOV M ON M.NUMTRANSENT = E.NUMTRANSENT
        JOIN BI_SINC_PRODUTO PR ON PR.CODPROD = M.CODPROD
        LEFT JOIN PCPRODUT P ON P.CODPROD = M.CODPROD
        LEFT JOIN PCMOVCOMPLE MC ON MC.NUMTRANSITEM = M.NUMTRANSITEM
        LEFT JOIN CUSTO_TV9 T ON T.NUMTRANSITEM_ENTTV9 = M.NUMTRANSITEM
       WHERE E.ESPECIE IN ('NF', 'NC', 'OE')
         AND M.STATUS IN ('A', 'AB')
         AND M.NUMTRANSITEM IS NOT NULL),
    
     BASE_VLOUTRASDESP AS
     (SELECT NUMTRANSVENDA,
             (CASE
               WHEN NVL(MAX(VLOUTRASDESP), 0) > 0 THEN
                'S'
               ELSE
                'N'
             END) AS CONSIDERA_OUTRASDESP
        FROM PCNFBASESAID
       WHERE TIPOVENDA = 'DF'
       GROUP BY NUMTRANSVENDA),
    
     PARCELAMENTO_PLPAG AS
     (SELECT PL.CODPLPAG,
             ROUND((NVL(PL.PRAZO1, 0) + NVL(PL.PRAZO2, 0) + NVL(PL.PRAZO3, 0) +
                   NVL(PL.PRAZO4, 0) + NVL(PL.PRAZO5, 0) + NVL(PL.PRAZO6, 0) +
                   NVL(PL.PRAZO7, 0) + NVL(PL.PRAZO8, 0) + NVL(PL.PRAZO9, 0) +
                   NVL(PL.PRAZO10, 0) + NVL(PL.PRAZO11, 0) + NVL(PL.PRAZO12, 0)) /
                   DECODE(PL.NUMDIAS, 0, 1, PL.NUMDIAS)) QTPARCELA
        FROM PCPLPAG PL),
    
     PARCELAMENTO_PRESTECF AS
     (SELECT E.NUMPED,
             COUNT(E.PRESTECF) QTPARCELA
        FROM PCPRESTECF E
       WHERE E.CODCOB NOT IN ('CRED')
       GROUP BY E.NUMPED),
    
     COBRANCA_CARTAO AS
     (SELECT B.CODCOB,
             B.CODCOBCC,
             NVL(MAX(B.PRAZOCC), 0) PRAZOPARCELA
        FROM PCCOB B
       WHERE B.CODCOBCC IS NOT NULL
       GROUP BY B.CODCOB,B.CODCOBCC),
     
     MOVT7 AS
     (SELECT M.NUMTRANSVENDA,
             M.NUMTRANSITEM AS NUMTRANSITEM_TV7,
             M.CODPROD,
             M.CUSTOCONT AS CUSTOCONT_TV7
        FROM PCMOV M
       INNER JOIN PCNFSAID S ON M.NUMTRANSVENDA = S.NUMTRANSVENDA
       WHERE S.CONDVENDA = 7),
    
     CUSTOCONT_TV8 AS
     (SELECT M8.NUMTRANSITEM AS NUMTRANSITEM_TV8,
             T7.CUSTOCONT_TV7
        FROM PCMOV M8
       INNER JOIN PCPEDC C ON M8.NUMTRANSVENDA = C.NUMTRANSVENDA
       INNER JOIN PCNFSAID S ON C.NUMPEDENTFUT = S.NUMPED
       INNER JOIN MOVT7 T7 ON S.NUMTRANSVENDA = T7.NUMTRANSVENDA AND M8.CODPROD = T7.CODPROD
       WHERE C.CONDVENDA = 8),
    
     SAIDAS AS
     (SELECT M.NUMTRANSITEM,
             'S' MOVIMENTO,
             (CASE
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_BONIFICADA) THEN 'SAIDA BONIFICADA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_CONSERTO) THEN 'SAIDA CONSERTO'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_DEMONSTRACAO) THEN 'SAIDA DEMONSTRACAO'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_DESCONSIDERAR) THEN 'SAIDA DESCONSIDERAR'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_DEVOLUCAO) THEN 'SAIDA DEVOLUCAO'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_DEV_CONSIGNADO) THEN 'SAIDA DEVOLUCAO CONSIGNADO'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_FAT_CONTA_ORDEM) THEN 'SAIDA FAT CONTA E ORDEM'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_FAT_ENTREGA_FUTURA) THEN 'SAIDA FAT ENTREGA FUTURA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_PERDA_MERCADORIA) THEN 'SAIDA PERDA MERCADORIA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_REM_CONTA_ORDEM) THEN 'SAIDA REM CONTA E ORDEM'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_REM_ENTREGA_FUTURA) THEN 'SAIDA REM ENTREGA FUTURA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_SIMPLES_REMESSA) THEN 'SAIDA SIMPLES REMESSA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_TRANSFERENCIA) THEN 'SAIDA TRANSFERENCIA'
               WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_VENDA) THEN 'SAIDA VENDA'
               ELSE 'SAIDA NAO INFORMADA'
             END) TIPOMOV,
             NVL(M.CODFILIALNF, M.CODFILIAL) CODFILIAL,
             M.NUMTRANSVENDA NUMTRANSACAO,
             (CASE WHEN NVL(S.NUMTRANSVENDAORIGEM,0) <> 0 THEN 'S' ELSE 'N' END) TEMVENDAORIG,
             S.CODCOB,
             (CASE
               WHEN S.CODCOB = 'CRED' THEN 1
               WHEN S.SERIE = 'SF' AND (S.CODCOB IN ('CONV', 'D', 'PIXL') OR CC.CODCOBCC = 'CADB') THEN 1
               WHEN S.SERIE = 'SF' THEN PE.QTPARCELA
               ELSE PL.QTPARCELA
             END) PARCELAS,
             (CASE
               WHEN S.CODCOB = 'CRED' THEN 0
               WHEN S.SERIE = 'SF' THEN (PE.QTPARCELA * CC.PRAZOPARCELA)
               ELSE S.PRAZOMEDIO
             END) PRAZO,
             DECODE(NVL(M.CODUSUR,0),0, S.CODUSUR, M.CODUSUR) CODUSUR,
             0 CODFORNEC,
             S.CODCLI,
             M.NUMNOTA,
             M.DTMOV DATA,
             M.CODPROD,
             M.QTCONT QT,
             ROUND(NVL(M.CUSTOFINEST, M.CUSTOFIN) * M.QTCONT,4) CUSTOFINANCEIRO,
             ROUND(NVL(M.CUSTOREP, 0) * M.QTCONT,4) CUSTOREPOSICAO,
             (CASE 
                WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM vSAID_FAT_CONTA_ORDEM UNION SELECT CODFISCAL FROM vSAID_REM_ENTREGA_FUTURA) THEN ROUND(NVL(T.CUSTOCONT_TV7, 0) * M.QTCONT,4)
                ELSE ROUND(NVL(M.CUSTOCONT, 0) * M.QTCONT,4) 
             END) CUSTOCONTABIL,
             (CASE
               WHEN (NVL(M.CODOPER, 'X') <> 'SD') THEN ROUND(M.QTCONT * (M.PUNITCONT + NVL(M.VLFRETE, 0) + NVL(M.VLOUTROS, 0)), 2)
               ELSE
                (CASE WHEN B.CONSIDERA_OUTRASDESP = 'S' THEN  ROUND(M.QTCONT * (ROUND(M.PUNITCONT, 6) + NVL(ROUND(M.VLOUTRASDESP, 2), 0)), 2)
                      ELSE ROUND(M.QTCONT * ROUND(M.PUNITCONT, 6), 2)
                END)
             END) AS VLCONTABIL,
             ROUND(M.PUNITCONT,4) PUNIT,
             ROUND(M.PTABELA,4) PTABELA,
             (CASE
               WHEN (NVL(M.CODOPER, 'X') <> 'SDF') THEN ROUND(M.QTCONT * (M.PUNITCONT - NVL(M.ST, 0) - NVL(M.VLIPI, 0)), 2)
               ELSE ROUND(M.QTCONT * (M.PUNITCONT - NVL(M.ST, 0) - NVL(M.VLIPI, 0) - NVL(M.VLFRETE, 0)), 2)
             END) VLPRODUTO,
             ROUND(M.QTCONT * NVL(M.VLDESCONTO, 0), 2) VLDESCONTO,
             (CASE
               WHEN LENGTH(M.SITTRIBUT) = 1 THEN LPAD(M.SITTRIBUT, 2, '0')
               ELSE M.SITTRIBUT
             END) CST_ICMS,
             M.CODFISCAL CFOP,
             ROUND(M.QTCONT * (NVL(M.BASEICMS, 0) + NVL(MC.VLBASEFRETE, 0) + NVL(MC.VLBASEOUTROS, 0)), 2) VLBASEICMS,
             ROUND((NVL(M.PERCICM, 0) / 100),4) PERCICMS,
             ROUND(M.QTCONT * NVL(MC.VLICMS, (NVL(M.BASEICMS, 0) + NVL(MC.VLBASEFRETE, 0) + NVL(MC.VLBASEOUTROS, 0)) * NVL(M.PERCICM, 0) / 100), 2) VLICMS,
             (CASE
               WHEN (M.DTMOV >= vDT_INICIO_BENEFICIO_ES AND M.CODFILIAL = '11' AND M.PERCICM > 0 AND NVL(M.GERAICMSLIVROFISCAL, 'S') = 'S') 
                 THEN ROUND(vALIQ_ICMS_ES_BENEFICIO * (M.QTCONT * (NVL(M.BASEICMS, 0) + NVL(MC.VLBASEFRETE, 0) + NVL(MC.VLBASEOUTROS, 0))),4)
               ELSE 0
             END) VLICMSBENEFICIO,
             ROUND(M.QTCONT * NVL(M.ST, 0), 2) VLST,
             ROUND(M.QTCONT * NVL(M.VLDESPADICIONAL, 0), 2) VLSTGUIA,
             ROUND((NVL(M.PERCIPI, 0) / 100),4) PERCIPI,
             ROUND(M.QTCONT * NVL(M.VLIPI, 0), 2) VLIPI,
             (CASE
               WHEN LENGTH(M.CODSITTRIBPISCOFINS) = 1 THEN LPAD(TO_CHAR(M.CODSITTRIBPISCOFINS), 2, '0')
               ELSE TO_CHAR(M.CODSITTRIBPISCOFINS)
             END) CST_PISCOFINS,
             ROUND(M.QTCONT * NVL(M.VLBASEPISCOFINS, 0), 2) VLBASEPISCOFINS,
             ROUND((M.PERPIS / 100),4) PERCPIS,
             ROUND((M.PERCOFINS / 100),4) PERCCOFINS,
             ROUND(M.QTCONT * NVL(M.VLPIS, 0), 2) VLPIS,
             ROUND(M.QTCONT * NVL(M.VLCOFINS, 0), 2) VLCOFINS,
             ROUND(M.QTCONT * NVL(M.VLFRETE, 0), 2) VLFRETE,
             ROUND(M.QTCONT * NVL(M.VLOUTRASDESP, 0), 2) VLOUTRASDESP,
             (ROUND(NVL(M.QTCONT, 0) * NVL(MC.VLICMSPARTREM, 0), 2) + ROUND(NVL(M.QTCONT, 0) * NVL(MC.VLICMSPARTDEST, 0), 2) + ROUND(NVL(M.QTCONT, 0) * NVL(MC.VLFCPPART, 0), 2)) VLICMSDIFAL,
             M.DTCANCEL
    FROM PCNFSAID S
    JOIN PCMOV M ON M.NUMTRANSVENDA = S.NUMTRANSVENDA
    JOIN BI_SINC_PRODUTO PR ON PR.CODPROD = M.CODPROD
    LEFT JOIN PCPRODUT P ON P.CODPROD = M.CODPROD
    LEFT JOIN PCMOVCOMPLE MC ON MC.NUMTRANSITEM = M.NUMTRANSITEM
    LEFT JOIN BASE_VLOUTRASDESP B ON B.NUMTRANSVENDA = S.NUMTRANSVENDA
    LEFT JOIN PARCELAMENTO_PLPAG PL ON PL.CODPLPAG = S.CODPLPAG
    LEFT JOIN PARCELAMENTO_PRESTECF PE ON PE.NUMPED = S.NUMPED
    LEFT JOIN COBRANCA_CARTAO CC ON CC.CODCOB = S.CODCOB
    LEFT JOIN CUSTOCONT_TV8 T ON T.NUMTRANSITEM_TV8 = M.NUMTRANSITEM
   WHERE M.STATUS IN ('A', 'AB')
     AND M.NUMTRANSITEM IS NOT NULL),
    
     MOVIMENTACAO AS
     (SELECT E.*, 
             E.CUSTOFINANCEIRO + E.VLICMS + E.VLPIS + E.VLCOFINS VLCMVGERENCIAL,
             E.CUSTOCONTABIL + E.VLICMS + E.VLPIS + E.VLCOFINS VLCMVCONTABIL
        FROM ENTRADAS E 
        UNION ALL 
      SELECT S.*,
             (CASE WHEN S.VLICMSBENEFICIO > 0 
                  THEN S.CUSTOFINANCEIRO + S.VLICMSBENEFICIO + S.VLPIS + S.VLCOFINS
                  ELSE S.CUSTOFINANCEIRO + S.VLICMS + S.VLPIS + S.VLCOFINS
              END) VLCMVGERENCIAL,
              (CASE WHEN S.VLICMSBENEFICIO > 0 
                  THEN S.CUSTOCONTABIL + S.VLICMSBENEFICIO + S.VLPIS + S.VLCOFINS
                  ELSE S.CUSTOCONTABIL + S.VLICMS + S.VLPIS + S.VLCOFINS
              END) VLCMVCONTABIL
       FROM SAIDAS S)
    
     SELECT M.NUMTRANSITEM,
            M.MOVIMENTO,
            M.TIPOMOV,
            M.CODFILIAL,
            M.NUMTRANSACAO,
            M.TEMVENDAORIG,
            M.CODCOB,
            M.PARCELAS,
            M.PRAZO,
            M.CODUSUR,
            M.CODFORNEC,
            M.CODCLI,
            M.NUMNOTA,
            M.DATA,
            M.CODPROD,
            M.QT,
            M.CUSTOFINANCEIRO,
            M.CUSTOREPOSICAO,
            M.CUSTOCONTABIL,
            M.VLCONTABIL,
            M.PUNIT,
            M.PTABELA,
            M.VLPRODUTO,
            M.VLDESCONTO,
            M.CST_ICMS,
            M.CFOP,
            M.VLBASEICMS,
            M.PERCICMS,
            M.VLICMS,
            M.VLICMSBENEFICIO,
            M.VLST,
            M.VLSTGUIA,
            M.PERCIPI,
            M.VLIPI,
            M.CST_PISCOFINS,
            M.VLBASEPISCOFINS,
            M.PERCPIS,
            M.PERCCOFINS,
            M.VLPIS,
            M.VLCOFINS,
            M.VLFRETE,
            M.VLOUTRASDESP,
            M.VLICMSDIFAL,
            M.VLCMVGERENCIAL,
            M.VLCMVCONTABIL,
            M.DTCANCEL
      FROM MOVIMENTACAO M
      LEFT JOIN BI_SINC_MOV_PRODUTO S ON S.NUMTRANSITEM = M.NUMTRANSITEM
     WHERE 1 = 1 
       AND M.DATA >= vDATA_MOV_INCREMENTAL
       AND (S.DT_UPDATE IS NULL
        OR (NVL(S.CODFORNEC,99999) <> M.CODFORNEC)
        OR (NVL(S.CODCLI,99999) <> M.CODCLI)
        OR NVL(S.CFOP,0) <> M.CFOP
        OR NVL(S.NUMNOTA,0) <> M.NUMNOTA
        OR NVL(S.DATA,TO_DATE('01/01/1889','DD/MM/YYYY')) <> M.DATA
        OR NVL(S.CODUSUR,999) <> M.CODUSUR
        OR NVL(S.TEMVENDAORIG,'0') <> M.TEMVENDAORIG
        OR NVL(S.CUSTOFINANCEIRO,0) <> M.CUSTOFINANCEIRO
        OR NVL(S.CUSTOREPOSICAO,0) <> M.CUSTOREPOSICAO
        OR NVL(S.CUSTOCONTABIL,0) <> M.CUSTOCONTABIL
        OR NVL(S.VLPRODUTO,0) <> M.VLPRODUTO
        OR NVL(S.CST_ICMS,'0') <> M.CST_ICMS
        OR NVL(S.VLBASEICMS,0) <> M.VLBASEICMS
        OR NVL(S.PERCICMS,0) <> M.PERCICMS
        OR NVL(S.VLICMSBENEFICIO,0) <> M.VLICMSBENEFICIO
        OR NVL(S.PERCIPI,0) <> M.PERCIPI
        OR NVL(S.CST_PISCOFINS,'0') <> M.CST_PISCOFINS
        OR NVL(S.VLBASEPISCOFINS,0) <> M.VLBASEPISCOFINS
        OR NVL(S.PERCPIS,0) <> M.PERCPIS
        OR NVL(S.PERCCOFINS,0) <> M.PERCCOFINS
        OR NVL(S.VLICMSDIFAL,0) <> M.VLICMSDIFAL
        OR NVL(S.VLCMVGERENCIAL,0) <> M.VLCMVGERENCIAL
        OR NVL(S.VLCMVCONTABIL,0) <> M.VLCMVCONTABIL
        OR NVL(S.DTCANCEL,TO_DATE('01/01/1889','DD/MM/YYYY')) <> M.DTCANCEL)
)

  -- Atualiza ou insere os resultados na tabela BI_SINC conforme as condições mencionadas

  LOOP
    BEGIN
      UPDATE BI_SINC_MOV_PRODUTO
         SET MOVIMENTO       = r.MOVIMENTO,
             TIPOMOV         = r.TIPOMOV,
             CODFILIAL       = r.CODFILIAL,
             NUMTRANSACAO    = r.NUMTRANSACAO,
             TEMVENDAORIG    = r.TEMVENDAORIG,
             CODCOB          = r.CODCOB,
             PARCELAS        = r.PARCELAS,
             PRAZO           = r.PRAZO,
             CODUSUR         = r.CODUSUR,
             CODFORNEC       = r.CODFORNEC,
             CODCLI          = r.CODCLI,
             NUMNOTA         = r.NUMNOTA,
             DATA            = r.DATA,
             CODPROD         = r.CODPROD,
             QT              = r.QT,
             CUSTOFINANCEIRO = r.CUSTOFINANCEIRO,
             CUSTOREPOSICAO  = r.CUSTOREPOSICAO,
             CUSTOCONTABIL   = r.CUSTOCONTABIL,
             VLCONTABIL      = r.VLCONTABIL,
             PUNIT           = r.PUNIT,
             PTABELA         = r.PTABELA,
             VLPRODUTO       = r.VLPRODUTO,
             VLDESCONTO      = r.VLDESCONTO,
             CST_ICMS        = r.CST_ICMS,
             CFOP            = r.CFOP,
             VLBASEICMS      = r.VLBASEICMS,
             PERCICMS        = r.PERCICMS,
             VLICMS          = r.VLICMS,
             VLICMSBENEFICIO = r.VLICMSBENEFICIO,
             VLST            = r.VLST,
             VLSTGUIA        = r.VLSTGUIA,
             PERCIPI         = r.PERCIPI,
             VLIPI           = r.VLIPI,
             CST_PISCOFINS   = r.CST_PISCOFINS,
             VLBASEPISCOFINS = r.VLBASEPISCOFINS,
             PERCPIS         = r.PERCPIS,
             PERCCOFINS      = r.PERCCOFINS,
             VLPIS           = r.VLPIS,
             VLCOFINS        = r.VLCOFINS,
             VLFRETE         = r.VLFRETE,
             VLOUTRASDESP    = r.VLOUTRASDESP,
             VLICMSDIFAL     = r.VLICMSDIFAL,
             VLCMVGERENCIAL  = r.VLCMVGERENCIAL,
             VLCMVCONTABIL   = r.VLCMVCONTABIL,
             DTCANCEL        = r.DTCANCEL,
             DT_UPDATE       = SYSDATE
       WHERE NUMTRANSITEM = r.NUMTRANSITEM;
      IF SQL%NOTFOUND
      THEN
        INSERT INTO BI_SINC_MOV_PRODUTO
          (NUMTRANSITEM,
           MOVIMENTO,
           TIPOMOV,
           CODFILIAL,
           NUMTRANSACAO,
           TEMVENDAORIG,
           CODCOB,
           PARCELAS,
           PRAZO,
           CODUSUR,
           CODFORNEC,
           CODCLI,
           NUMNOTA,
           DATA,
           CODPROD,
           QT,
           CUSTOFINANCEIRO,
           CUSTOREPOSICAO,
           CUSTOCONTABIL,
           VLCONTABIL,
           PUNIT,
           PTABELA,
           VLPRODUTO,
           VLDESCONTO,
           CST_ICMS,
           CFOP,
           VLBASEICMS,
           PERCICMS,
           VLICMS,
           VLICMSBENEFICIO,
           VLST,
           VLSTGUIA,
           PERCIPI,
           VLIPI,
           CST_PISCOFINS,
           VLBASEPISCOFINS,
           PERCPIS,
           PERCCOFINS,
           VLPIS,
           VLCOFINS,
           VLFRETE,
           VLOUTRASDESP,
           VLICMSDIFAL,
           VLCMVGERENCIAL,
           VLCMVCONTABIL,
           DTCANCEL,
           DT_UPDATE)
        VALUES
          (r.NUMTRANSITEM,
           r.MOVIMENTO,
           r.TIPOMOV,
           r.CODFILIAL,
           r.NUMTRANSACAO,
           r.TEMVENDAORIG,
           r.CODCOB,
           r.PARCELAS,
           r.PRAZO,
           r.CODUSUR,
           r.CODFORNEC,
           r.CODCLI,
           r.NUMNOTA,
           r.DATA,
           r.CODPROD,
           r.QT,
           r.CUSTOFINANCEIRO,
           r.CUSTOREPOSICAO,
           r.CUSTOCONTABIL,
           r.VLCONTABIL,
           r.PUNIT,
           r.PTABELA,
           r.VLPRODUTO,
           r.VLDESCONTO,
           r.CST_ICMS,
           r.CFOP,
           r.VLBASEICMS,
           r.PERCICMS,
           r.VLICMS,
           r.VLICMSBENEFICIO,
           r.VLST,
           r.VLSTGUIA,
           r.PERCIPI,
           r.VLIPI,
           r.CST_PISCOFINS,
           r.VLBASEPISCOFINS,
           r.PERCPIS,
           r.PERCCOFINS,
           r.VLPIS,
           r.VLCOFINS,
           r.VLFRETE,
           r.VLOUTRASDESP,
           r.VLICMSDIFAL,
           r.VLCMVGERENCIAL,
           r.VLCMVCONTABIL,
           r.DTCANCEL,
           SYSDATE);
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro encontrado: ' || SQLERRM);
        RAISE_APPLICATION_ERROR(-20000,
                                'Erro durante a insercao na tabela: ' ||
                                SQLERRM);
    END;
  END LOOP;

  COMMIT;
END;
