CREATE OR REPLACE VIEW VIEW_BI_SINC_SALDO_BANCO AS
  
  WITH ULTIMO_SALDO AS
   (SELECT M.CODBANCO,
           M.DATACOMPLETA,
           M.VLSALDO,
           M.DTCONCIL,
           M.VLSALDOCONCIL,
           ROW_NUMBER() OVER (PARTITION BY M.CODBANCO ORDER BY M.DATACOMPLETA DESC) AS RN
      FROM PCMOVCR M
     WHERE M.CODCOB = 'D'
       AND M.DTESTORNO IS NULL
     ORDER BY M.CODBANCO,
              M.DATACOMPLETA DESC),
  
  ULTIMO_SALDO_CONCILIADO AS
   (SELECT M.CODBANCO,
           M.DTCONCIL,
           M.VLSALDOCONCIL,
           ROW_NUMBER() OVER (PARTITION BY M.CODBANCO ORDER BY M.DTCONCIL DESC) AS RN
      FROM PCMOVCR M
     WHERE M.CODCOB = 'D'
       AND M.DTESTORNO IS NULL
       AND M.DTCONCIL IS NOT NULL
     ORDER BY M.CODBANCO,
              M.DATACOMPLETA DESC)
  
  SELECT B.CODFILIAL,
         M.CODBANCO,
         B.NOME BANCO,
         B.TIPOCXBCO,
         M.DATACOMPLETA DATA,
         M.VLSALDO,
         D.DTCONCIL DTCONCIL,
         D.VLSALDOCONCIL
    FROM ULTIMO_SALDO M
    LEFT JOIN ULTIMO_SALDO_CONCILIADO D ON M.CODBANCO = D.CODBANCO
    LEFT JOIN PCBANCO B ON B.CODBANCO = M.CODBANCO
   WHERE M.RN = 1
     AND D.RN = 1
     AND B.TIPOCXBCO NOT IN ('I')
     AND B.FLUXOCX = 'S'
     AND M.VLSALDO <> 0;
