CREATE OR ALTER PROCEDURE SP_RETORNA_VENDEDOR
    @CODVENDEDOR INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM VENDEDOR WHERE CODVENDEDOR = @CODVENDEDOR)
    BEGIN
        SELECT FORMAT(DTUPDATE, 'yyyy-MM-dd HH:mm:ss') DTUPDATE FROM VENDEDOR WHERE CODVENDEDOR = @CODVENDEDOR
    END
END