CREATE OR REPLACE PROCEDURE PRC_RETORNA_VENDEDOR
(
  pCODUSUR  IN PCUSUARI.CODUSUR%TYPE,
  pDTUPDATE IN TIMESTAMP
) AS
BEGIN
  UPDATE BI_SINC_VENDEDOR SET DT_SINC = pDTUPDATE WHERE CODUSUR = pCODUSUR;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Nenhum registro encontrado para a marca ' ||
                         TO_CHAR(pCODUSUR));
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro inesperado:' || SQLERRM);
  
END;
