CREATE OR ALTER PROCEDURE SP_RETORNA_ESTOQUE
    @CODFILIAL NVARCHAR(2),
    @CODPROD   INT
AS
BEGIN    
    IF EXISTS (SELECT 1 FROM ESTOQUE WHERE CODFILIAL = @CODFILIAL AND CODPROD = @CODPROD)
	SELECT FORMAT(DTUPDATE, 'yyyy-MM-dd HH:mm:ss') DTUPDATE FROM ESTOQUE WHERE CODFILIAL = @CODFILIAL AND CODPROD = @CODPROD
END