CREATE OR REPLACE PROCEDURE PRC_RETORNA_ESTOQUE
(
  pCODFILIAL IN PCEST.CODFILIAL%TYPE,
  pCODPROD   IN PCEST.CODPROD%TYPE,
  pDTUPDATE  IN TIMESTAMP
) AS
BEGIN
  UPDATE BI_SINC_ESTOQUE
     SET DT_SINC = pDTUPDATE
   WHERE CODFILIAL = pCODFILIAL
     AND CODPROD = pCODPROD;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Nenhum registro encontrado para a filial ' ||
                         TO_CHAR(pCODFILIAL) || 'e produto ' ||
                         TO_CHAR(pCODPROD));
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro inesperado:' || SQLERRM);
END;
