CREATE OR ALTER PROCEDURE SP_CARREGA_MARCA
    @CODMARCA SMALLINT,
    @MARCA   NVARCHAR (40),
    @ATIVO    CHAR (1)
AS
BEGIN    
    ----faz o merge das informações
        IF EXISTS (SELECT 1 FROM MARCA WHERE CODMARCA = @CODMARCA)
			BEGIN
			UPDATE MARCA SET MARCA = @MARCA, ATIVO = @ATIVO WHERE CODMARCA = @CODMARCA
		END
    	ELSE
			BEGIN
			INSERT INTO MARCA (CODMARCA, MARCA, ATIVO)
			VALUES (@CODMARCA, @MARCA, @ATIVO)
	END
END