CREATE OR REPLACE PROCEDURE PRC_RETORNA_PRODUTO
(
  pCODPROD  IN PCPRODUT.CODPROD%TYPE,
  pDTUPDATE IN TIMESTAMP
) AS
BEGIN
  UPDATE BI_SINC_PRODUTO SET DT_SINC = pDTUPDATE WHERE CODPROD = pCODPROD;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Nenhum registro encontrado para a marca ' ||
                         TO_CHAR(pCODPROD));
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro inesperado:' || SQLERRM);
  
END;
