CREATE OR ALTER PROCEDURE SP_CARREGA_PRODUTO
    @CODPROD INT,
    @PRODUTO NVARCHAR (40),
    @CODDEPTO INT,
    @DEPARTAMENTO NVARCHAR (40),
    @CODSECAO INT,
    @SECAO NVARCHAR (40),
    @CODCATEGORIA INT,
    @CATEGORIA NVARCHAR (40),
    @CODLINHA INT,
    @LINHA NVARCHAR (40),
    @CODFORNEC INT,
    @CODMARCA INT,
    @CODFABRICA NVARCHAR (30),
    @CODBARRAS INT,
    @CODBARRASMASTER INT,
    @PESO NUMERIC (12, 6),
    @LARGURA NUMERIC (10, 6),
    @ALTURA NUMERIC (10, 6),
    @COMPRIMENTO NUMERIC (10, 6),
    @VOLUME NUMERIC (20, 8),
    @QTCXMASTER NUMERIC (8, 2),
    @IMPORTADO CHAR (1),
    @REVENDA CHAR (1),
    @NCM NVARCHAR (15),
    @NCMEX NVARCHAR (20),
    @TIPOMERCADORIA NVARCHAR (15),
    @FORALINHA CHAR (1),
    @CERTIFICACAO NVARCHAR (200),
    @DTEXCLUSAO DATETIME
AS
BEGIN
    DECLARE @DTUPDATE DATETIME = DATEADD(HOUR, -3, GETUTCDATE())

    IF EXISTS (SELECT 1 FROM PRODUTO WHERE CODPROD = @CODPROD)
    BEGIN
        UPDATE PRODUTO
        SET PRODUTO = @PRODUTO,
            CODDEPTO = @CODDEPTO,
            DEPARTAMENTO = @DEPARTAMENTO,
            CODSECAO = @CODSECAO,
            SECAO = @SECAO,
            CODCATEGORIA = @CODCATEGORIA,
            CATEGORIA = @CATEGORIA,
            CODLINHA = @CODLINHA,
            LINHA = @LINHA,
            CODFORNEC = @CODFORNEC,
            CODMARCA = @CODMARCA,
            CODFABRICA = @CODFABRICA,
            CODBARRAS = @CODBARRAS,
            CODBARRASMASTER = @CODBARRASMASTER,
            PESO = @PESO,
            LARGURA = @LARGURA,
            ALTURA = @ALTURA,
            COMPRIMENTO = @COMPRIMENTO,
            VOLUME = @VOLUME,
            QTCXMASTER = @QTCXMASTER,
            IMPORTADO = @IMPORTADO,
            REVENDA = @REVENDA,
            NCM = @NCM,
            NCMEX = @NCMEX,
            TIPOMERCADORIA = @TIPOMERCADORIA,
            FORALINHA = @FORALINHA,
            CERTIFICACAO = @CERTIFICACAO,
            DTEXCLUSAO = @DTEXCLUSAO,
            DTUPDATE = @DTUPDATE
        WHERE CODPROD = @CODPROD
    END
    ELSE 
    BEGIN
        INSERT INTO PRODUTO (
                    CODPROD,
                    PRODUTO,
                    CODDEPTO,
                    DEPARTAMENTO,
                    CODSECAO,
                    SECAO,
                    CODCATEGORIA,
                    CATEGORIA,
                    CODLINHA,
                    LINHA,
                    CODFORNEC,
                    CODMARCA,
                    CODFABRICA,
                    CODBARRAS,
                    CODBARRASMASTER,
                    PESO,
                    LARGURA,
                    ALTURA,
                    COMPRIMENTO,
                    VOLUME,
                    QTCXMASTER,
                    IMPORTADO,
                    REVENDA,
                    NCM,
                    NCMEX,
                    TIPOMERCADORIA,
                    FORALINHA,
                    CERTIFICACAO,
                    DTEXCLUSAO,
                    DTUPDATE)
            VALUES (
                    @CODPROD,
                    @PRODUTO,
                    @CODDEPTO,
                    @DEPARTAMENTO,
                    @CODSECAO,
                    @SECAO,
                    @CODCATEGORIA,
                    @CATEGORIA,
                    @CODLINHA,
                    @LINHA,
                    @CODFORNEC,
                    @CODMARCA,
                    @CODFABRICA,
                    @CODBARRAS,
                    @CODBARRASMASTER,
                    @PESO,
                    @LARGURA,
                    @ALTURA,
                    @COMPRIMENTO,
                    @VOLUME,
                    @QTCXMASTER,
                    @IMPORTADO,
                    @REVENDA,
                    @NCM,
                    @NCMEX,
                    @TIPOMERCADORIA,
                    @FORALINHA,
                    @CERTIFICACAO,
                    @DTEXCLUSAO,
                    @DTUPDATE)
    END
END