----USADO PARA FAZER O TRATAMENTO DA MOVIMENTAÇÃO DE PRODUTOS NO PADRAO CONTABILIDADE
DROP TYPE T_MOV_PROD_BASE_TABLE;
DROP TYPE T_MOV_PROD_BASE_RECORD;


CREATE OR REPLACE TYPE T_MOV_PROD_BASE_TABLE IS TABLE OF T_MOV_PROD_BASE_RECORD;
CREATE OR REPLACE TYPE T_MOV_PROD_BASE_RECORD IS OBJECT
(
  CODEMPRESA         VARCHAR2(2),
  CODFILIAL          VARCHAR2(2),
  DATA               DATE,
  MOVIMENTO       VARCHAR2(1),
  TIPOMOV            VARCHAR2(60),
  NUMTRANSACAO       NUMBER,
  TEMVENDAORIG       VARCHAR2(1),
  NUMNOTA            NUMBER,
  CODSUPERVISOR      NUMBER,
  CODGERENTE         NUMBER,
  DTCANCEL           DATE,
  CODFORNEC          NUMBER(6),
  FORNECEDOR         VARCHAR2(80),
  CLIENTE            VARCHAR2(80),
  CUSTOCONTABIL      NUMBER(12, 2),
  VALORCONTABIL      NUMBER(12, 2),
  VALORST            NUMBER(12, 2),
  VALORSTGUIA        NUMBER(12, 2),
  VALORICMS          NUMBER(12, 2),
  VALORICMSBENEFICIO NUMBER(12, 2),
  VALORICMSDIFAL     NUMBER(12, 2),
  VALORPIS           NUMBER(12, 2),
  VALORCOFINS        NUMBER(12, 2)
)
;

CREATE OR REPLACE TYPE T_MOV_PROD_CONTABIL_TABLE IS TABLE OF T_MOV_PROD_CONTABIL_RECORD;
CREATE OR REPLACE TYPE T_MOV_PROD_CONTABIL_RECORD IS OBJECT
(
  CODEMPRESA      VARCHAR2(2),
  DATA            DATE,
  TIPOLANCAMENTO  NUMBER,
  IDENTIFICADOR   NUMBER,
  DOCUMENTO       NUMBER,
  CONTADEBITO     NUMBER,
  CONTACREDITO    NUMBER,
  CODCC_DEBITO    VARCHAR2(4),
  CODCC_CREDITO   VARCHAR2(4),
  ATIVIDADE       VARCHAR2(120),
  HISTORICO       VARCHAR2(120),
  VALOR           NUMBER(12, 2),
  ORIGEM          VARCHAR2(80),
  ENVIAR_CONTABIL VARCHAR(1),
  DTCANCEL        DATE
)
;
