----USADO PARA FAZER O TRATAMENTO DA MOVIMENTAÇÃO DE PRODUTOS NO PADRAO CONTABILIDADE
DROP TYPE T_MOV_PROD_BASE_TABLE;
DROP TYPE T_MOV_PROD_BASE_RECORD;


CREATE OR REPLACE TYPE T_MOV_PROD_BASE_TABLE IS TABLE OF T_MOV_PROD_BASE_RECORD;
CREATE OR REPLACE TYPE T_MOV_PROD_BASE_RECORD IS OBJECT
(
  CODEMPRESA         VARCHAR2(2),
  CODFILIAL          VARCHAR2(2),
  DATA               DATE,
  TIPOMOV            VARCHAR2(60),
  NUMTRANSACAO       NUMBER,
  TEMVENDAORIG       VARCHAR2(1),
  NUMNOTA            NUMBER,
  CODSUPERVISOR      NUMBER,
  CODGERENTE         NUMBER,
  DTCANCEL           DATE,
  FORNECEDOR         VARCHAR2(80),
  CLIENTE            VARCHAR2(80),
  CUSTOCONTABIL      NUMBER(12, 2),
  VALORCONTABIL      NUMBER(12, 2),
  VALORST            NUMBER(12, 2),
  VALORSTGUIA        NUMBER(12, 2),
  VALORICMS          NUMBER(12, 2),
  VALORICMSBENEFICIO NUMBER(12, 2),
  VALORICMSDIFAL     NUMBER(12, 2),
  VALORPIS           NUMBER(12, 2),
  VALORCOFINS        NUMBER(12, 2)
)
;

