----USADO PARA FAZER O TRATAMENTO DA MOVIMENTAÇÃO DE PRODUTOS NO PADRAO CONTABILIDADE


---------MODELO PARA RECEBER OS LANCAMENTOS PARA CONTABILIDADE
DROP TYPE T_CONTABIL_TABLE;
DROP TYPE T_CONTABIL_RECORD;

CREATE OR REPLACE TYPE T_CONTABIL_TABLE IS TABLE OF T_CONTABIL_RECORD;
CREATE OR REPLACE TYPE T_CONTABIL_RECORD IS OBJECT
(
  CODLANC         VARCHAR2(3),
  CODEMPRESA      VARCHAR2(2),
  DATA            DATE,
  TIPOLANCAMENTO  NUMBER,
  IDENTIFICADOR   NUMBER,
  DOCUMENTO       NUMBER,
  CONTADEBITO     NUMBER,
  CONTACREDITO    NUMBER,
  CODCC_DEBITO    VARCHAR2(4),
  CODCC_CREDITO   VARCHAR2(4),
  ATIVIDADE       VARCHAR2(120),
  HISTORICO       VARCHAR2(150),
  VALOR           NUMBER(12, 2),
  ORIGEM          VARCHAR2(80),
  ENVIAR_CONTABIL VARCHAR2(1),
  DTCANCEL        DATE
)
;
--------FORNECEDORES DA JC BROTHERS
DROP TYPE T_FORNEC_JCBROTHERS_TABLE;
DROP TYPE T_FORNEC_JCBROTHERS_RECORD;

CREATE OR REPLACE TYPE T_FORNEC_JCBROTHERS_TABLE IS TABLE OF T_FORNEC_JCBROTHERS_RECORD;
CREATE OR REPLACE TYPE T_FORNEC_JCBROTHERS_RECORD IS OBJECT
(
  CODFORNEC NUMBER
)
;

--------CENTRO DE CUSTO POR FILIAL
DROP TYPE T_CC_FILIAL_TABLE;
DROP TYPE T_CC_FILIAL_RECORD;

CREATE OR REPLACE TYPE T_CC_FILIAL_TABLE IS TABLE OF T_CC_FILIAL_RECORD;
CREATE OR REPLACE TYPE T_CC_FILIAL_RECORD IS OBJECT
(
  CODFILIAL VARCHAR(2),
  CODCC     VARCHAR(3)
)
;

--------CENTRO DE CUSTO POR SUPERVISOR 
DROP TYPE T_CC_VENDEDOR_TABLE;
DROP TYPE T_CC_VENDEDOR_RECORD;

CREATE OR REPLACE TYPE T_CC_VENDEDOR_TABLE IS TABLE OF T_CC_VENDEDOR_RECORD;
CREATE OR REPLACE TYPE T_CC_VENDEDOR_RECORD IS OBJECT
(
  CODSUPERVISOR NUMBER,
  CODCC         VARCHAR(3)
)
;
