--CREATE OR REPLACE VIEW VIEW_BI_SINC_PLANO_CONTAS_ESTILO AS

    WITH EMPRESA AS
     (SELECT F.CODEMPRESA FROM BI_SINC_FILIAL F GROUP BY F.CODEMPRESA),
    
    PLANO_JC_EMPRESAS AS
     (SELECT E.CODEMPRESA,
             C.CONTA,
             C.CODCONTA,
             C.CONTAN1,
             C.CONTAN2,
             C.CONTAN3,
             C.CONTAN4
        FROM BI_SINC_PLANO_CONTAS_ESTILO C
       CROSS JOIN EMPRESA E
       ORDER BY C.ORDEM,
                E.CODEMPRESA)
    
  /*  PLANO_UNIFICADO AS
     (SELECT * FROM VIEW_BI_SINC_FORNEC_PLANO_CONTAS UNION ALL SELECT * FROM PLANO_JC_EMPRESAS)*/
		 
		 SELECT * FROM PLANO_JC_EMPRESAS;
    
    SELECT (C.CODCONTA || '-' || C.CODEMPRESA) IDCONTABIL,
           C.CODCLASSIFICA,
           C.CONTA,
           C.NIVEL,
           C.TIPOCONTA,
           C.CODGERENCIAL,
           C.CODCONTABIL,
           C.CODBALANCO,
           C.CODDRE,
           C.CODEBTIDA,
           C.CONTAN1,
           C.CONTAN2,
           C.CONTAN3,
           C.CONTAN4,
           C.CONTAN5
      FROM PLANO_UNIFICADO C
     ORDER BY CODCLASSIFICA;
