CREATE OR REPLACE VIEW VIEW_BI_SINC_CONTABILIDADE_DFC AS

 WITH DFC_AGG AS
  (SELECT C.CODDFC,
          C.CODEMPRESA,
          C.CODFILIAL,
          TO_DATE(TRUNC(TO_DATE(C.DATA, 'DD/MM/YYYY'), 'MM')) DATA,
          C.VALOR
     FROM BI_SINC_CONTABILIDADE C
    WHERE C.CODDFC_CTARAZAO = 5)
 
 SELECT CODDFC,
        CODEMPRESA,
        CODFILIAL,
        DATA,
        (SUM(VALOR) * -1) VALOR
   FROM DFC_AGG
  GROUP BY CODDFC,
           CODEMPRESA,
           CODFILIAL,
           DATA;
