CREATE OR ALTER PROCEDURE SP_CARREGA_COMPRADOR 
    @CODCOMPRADOR SMALLINT,
    @COMPRADOR NVARCHAR(15)
AS
BEGIN
    DECLARE @DTUPDATE DATETIME = DATEADD(hour, -3, GETUTCDATE())
    SET @COMPRADOR = CASE WHEN @COMPRADOR = 'NULL' THEN NULL ELSE TRIM(@COMPRADOR) END
    
    IF EXISTS (SELECT 1 FROM COMPRADOR WHERE CODCOMPRADOR = @CODCOMPRADOR)
    BEGIN
        UPDATE COMPRADOR 
        SET COMPRADOR = @COMPRADOR, DTUPDATE = @DTUPDATE 
        WHERE CODCOMPRADOR = @CODCOMPRADOR
    END
    ELSE
    BEGIN
        INSERT INTO COMPRADOR (CODCOMPRADOR, COMPRADOR, DTUPDATE)
        VALUES (@CODCOMPRADOR, @COMPRADOR,  @DTUPDATE)
    END
END