CREATE OR ALTER PROCEDURE SP_RETORNA_COMPRADOR
    @CODCOMPRADOR SMALLINT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM COMPRADOR WHERE CODCOMPRADOR = @CODCOMPRADOR)
    BEGIN
        SELECT FORMAT(DTUPDATE, 'yyyy-MM-dd HH:mm:ss') DTUPDATE FROM COMPRADOR WHERE CODCOMPRADOR = @CODCOMPRADOR
    END
END