CREATE OR REPLACE PROCEDURE PRC_RETORNA_COMPRADOR
(
  pCODCOMPRADOR IN PCEMPR.MATRICULA%TYPE,
  pDTUPDATE     IN TIMESTAMP
) AS
BEGIN
  UPDATE BI_SINC_COMPRADOR
     SET DT_SINC = pDTUPDATE
   WHERE MATRICULA = pCODCOMPRADOR;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Nenhum registro encontrado para a marca ' ||
                         TO_CHAR(pCODCOMPRADOR));
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro inesperado:' || SQLERRM);
  
END;
