CREATE OR REPLACE VIEW VIEW_BI_SINC_FORNEC_PLANO_CONTAS AS

  SELECT C.CODEMPRESA,
         C.CODCLASSIFICA,
         INITCAP(F.FORNECEDOR) CONTA,
         5 NIVEL,
         2 TIPOCONTA,
         C.CODFORNEC CODGERENCIAL,
         C.CODCONTABIL,
         2 CODBALANCO,
         NULL CODDRE,
         NULL CODEBTIDA,
         (CASE C.CODCLASSIFICA
           WHEN '2.1.1.01.001' THEN
            7 --MERCADORIA
           WHEN '2.1.1.02.001' THEN
            16 --IMOBILIZADO
           WHEN '2.1.1.03.001' THEN
            8 --TRANSPORTE
           ELSE
            9 --SERVICOS
         END) CODDFC,
         '2 - Passivo' CONTAN1,
         '2.1 - Passivo Circulante' CONTAN2,
         '2.1.1 - Fornecedores' CONTAN3,
         (SUBSTR(C.CODCLASSIFICA, 0, 8) || ' - ' ||
         (SELECT P.CONTA FROM BI_SINC_PLANO_CONTAS_JC P WHERE P.CODCLASSIFICA = C.CODCLASSIFICA)) CONTAN4,
         (INITCAP(F.FORNECEDOR) || ' - ' || F.CNPJ || ' - ' || C.CODFORNEC || ' - ' || C.CODCONTABIL) CONTAN5
    FROM BI_SINC_FORNECEDOR_CONTA C
    LEFT JOIN BI_SINC_FORNECEDOR F ON F.CODFORNEC = C.CODFORNEC
   ORDER BY F.FORNECEDOR
