CREATE OR REPLACE PROCEDURE PRC_SINC_FORNEC_INSERE_CONTA
(
  pCODEMPRESA IN VARCHAR2,
  pCODFORNEC  IN NUMBER,
  pCODCONTA   IN NUMBER
) AS


BEGIN
  -- Tenta atualizar o registro existente
  UPDATE BI_SINC_FORNECEDOR_CONTA
     SET CODCONTABIL   = pCODCONTA,
         DT_UPDATE     = SYSDATE
   WHERE CODEMPRESA = pCODEMPRESA
     AND CODFORNEC = pCODFORNEC;

  -- Se nenhum registro foi atualizado, insere um novo
  IF SQL%ROWCOUNT = 0 THEN
    INSERT INTO BI_SINC_FORNECEDOR_CONTA
      (CODEMPRESA,
       CODFORNEC,
       CODCONTABIL,
       CODCLASSIFICA,
       DT_UPDATE)
    VALUES
      (pCODEMPRESA,
       pCODFORNEC,
       pCODCONTA,
       NULL,
       SYSDATE);
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro encontrado: ' || SQLERRM);
    RAISE_APPLICATION_ERROR(-20000,
                            'Erro durante a insercao na tabela: ' || SQLERRM);
    COMMIT;
  
END;
