CREATE OR REPLACE PROCEDURE PRC_SINC_FORNEC_INSERE_CONTA
(
  pCODEMPRESA IN VARCHAR2,
  pCODFORNEC  IN NUMBER,
  pCODCONTA   IN NUMBER
) AS

  vTIPOFORNEC    VARCHAR2(1);
  vCODCLASSIFICA VARCHAR2(12);

BEGIN
  SELECT F.TIPO
    INTO vTIPOFORNEC
    FROM BI_SINC_FORNECEDOR F
   WHERE F.CODFORNEC = pCODFORNEC;

  IF vTIPOFORNEC = 'S' THEN
    vCODCLASSIFICA := '2.1.1.01.001'; --REVENDA
  ELSIF vTIPOFORNEC = 'X' THEN
    vCODCLASSIFICA := '2.1.1.02.001'; --IMOBILIZADO
  ELSE
    vCODCLASSIFICA := '2.1.1.03.002'; --OUTROS
  END IF;

  -- Tenta atualizar o registro existente
  UPDATE BI_SINC_FORNECEDOR_CONTA
     SET CODCONTABIL   = pCODCONTA,
         CODCLASSIFICA = vCODCLASSIFICA,
         DT_UPDATE     = SYSDATE
   WHERE CODEMPRESA = pCODEMPRESA
     AND CODFORNEC = pCODFORNEC;

  -- Se nenhum registro foi atualizado, insere um novo
  IF SQL%ROWCOUNT = 0 THEN
    INSERT INTO BI_SINC_FORNECEDOR_CONTA
      (CODEMPRESA,
       CODFORNEC,
       CODCONTABIL,
       CODCLASSIFICA,
       DT_UPDATE)
    VALUES
      (pCODEMPRESA,
       pCODFORNEC,
       pCODCONTA,
       vCODCLASSIFICA,
       SYSDATE);
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro encontrado: ' || SQLERRM);
    RAISE_APPLICATION_ERROR(-20000,
                            'Erro durante a insercao na tabela: ' || SQLERRM);
    COMMIT;
  
END;
