CREATE OR ALTER PROCEDURE SP_CARREGA_FORNECEDOR 
    @CODFORNEC INT,
    @FORNECEDOR NVARCHAR(60),
    @CNPJ NVARCHAR(18),
    @TIPO NVARCHAR(35)
AS
BEGIN
    DECLARE @DTUPDATE DATETIME = DATEADD(hour, -3, GETUTCDATE())
    SET @FORNECEDOR = CASE WHEN @FORNECEDOR = 'NULL' THEN NULL ELSE TRIM(@FORNECEDOR) END
    SET @CNPJ = CASE WHEN @CNPJ = 'NULL' THEN NULL ELSE TRIM(@CNPJ) END 
    SET @TIPO = CASE WHEN @TIPO = 'NULL' THEN NULL ELSE TRIM(@TIPO) END 
    
    IF EXISTS (SELECT 1 FROM FORNECEDOR WHERE CODFORNEC = @CODFORNEC)
    BEGIN
        UPDATE FORNECEDOR 
        SET FORNECEDOR = @FORNECEDOR, CNPJ = @CNPJ, TIPO = @TIPO, DTUPDATE = @DTUPDATE 
        WHERE CODFORNEC = @CODFORNEC
    END
    ELSE
    BEGIN
        INSERT INTO FORNECEDOR (CODFORNEC, FORNECEDOR, CNPJ, TIPO, DTUPDATE)
        VALUES (@CODFORNEC, @FORNECEDOR, @CNPJ, @TIPO, @DTUPDATE)
    END
END