CREATE OR ALTER PROCEDURE SP_RETORNA_FORNECEDOR
    @CODFORNEC INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FORNECEDOR WHERE CODFORNEC = @CODFORNEC)
    BEGIN
        SELECT FORMAT(DTUPDATE, 'yyyy-MM-dd HH:mm:ss') DTUPDATE FROM FORNECEDOR WHERE CODFORNEC = @CODFORNEC
    END
END