CREATE OR REPLACE FUNCTION FUNC_RATEAR_VALOR_POR_CC
(
  P_VALOR             IN NUMBER,
  P_RECNUM            IN NUMBER,
  P_CODIGOCENTROCUSTO IN VARCHAR2
) RETURN NUMBER IS

  -- VARIAVEIS DECLARADAS
  V_PERCRATEIO    NUMBER;
  V_VALOR_RATEADO NUMBER;
  V_SOMA_RATEADA  NUMBER := 0;
  V_AJUSTE        NUMBER;
  V_ULTIMO_CENTRO VARCHAR2(4);
BEGIN
  
	--VERIFICAR SE EXISTE O CC PASSADO
	IF P_CODIGOCENTROCUSTO = '0' THEN
    RETURN NULL;
  END IF;
	
	-- OBTER O PERCENTUAL DE RATEIO PARA O CENTRO DE CUSTO ESPECÍFICO
  SELECT R.PERCRATEIO
    INTO V_PERCRATEIO
    FROM PCRATEIOCENTROCUSTO R
   WHERE R.RECNUM = P_RECNUM
     AND R.CODIGOCENTROCUSTO = P_CODIGOCENTROCUSTO;

  IF V_PERCRATEIO IS NULL THEN
    RETURN NULL;
  END IF;

  -- CALCULAR O VALOR RATEADO
  V_VALOR_RATEADO := ROUND(P_VALOR * V_PERCRATEIO / 100, 2);

  -- CALCULAR A SOMA DOS VALORES RATEADOS PARA TODOS OS CENTROS DE CUSTO
  FOR REC IN (SELECT R.CODIGOCENTROCUSTO,
                     R.PERCRATEIO
                FROM PCRATEIOCENTROCUSTO R
               WHERE R.RECNUM = P_RECNUM)
  LOOP
    IF REC.CODIGOCENTROCUSTO = P_CODIGOCENTROCUSTO THEN
      V_SOMA_RATEADA := V_SOMA_RATEADA + V_VALOR_RATEADO;
    ELSE
      V_SOMA_RATEADA := V_SOMA_RATEADA + ROUND(P_VALOR * REC.PERCRATEIO / 100, 2);
    END IF;
    V_ULTIMO_CENTRO := REC.CODIGOCENTROCUSTO;
  END LOOP;         

  -- AJUSTAR O ÚLTIMO VALOR RATEADO PARA GARANTIR QUE A SOMA SEJA IGUAL AO VALOR ORIGINAL
  IF P_CODIGOCENTROCUSTO = V_ULTIMO_CENTRO THEN
    V_AJUSTE        := P_VALOR - V_SOMA_RATEADA;
    V_VALOR_RATEADO := V_VALOR_RATEADO + V_AJUSTE;
  END IF;

  RETURN V_VALOR_RATEADO;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    -- Tratar erro de forma mais específica
    RAISE_APPLICATION_ERROR(-20001, 
      'Centro de custo ' || P_CODIGOCENTROCUSTO || 
      ' não encontrado para o RECNUM ' || P_RECNUM || '.');
  WHEN OTHERS THEN
    -- Capturar outros erros não previstos
    RAISE_APPLICATION_ERROR(-20002, 
      'Erro ao processar rateio: ' || SQLERRM);    
END;
