CREATE OR REPLACE FUNCTION FUNC_RATEAR_VALOR_POR_CC(
                                                    
                                                    VALOR_NOTA  IN NUMBER,
                                                    PERCENTUAIS IN PERCENTUAIS_T) RETURN PERCENTUAIS_T
  PIPELINED IS
  VALOR_RATEADO NUMBER;
  SOMA_RATEADA  NUMBER := 0;
  AJUSTE        NUMBER;
BEGIN
  -- VERIFICAR SE A SOMA DOS PERCENTUAIS É 100%
  IF (SELECT SUM(COLUMN_VALUE) FROM TABLE(PERCENTUAIS)) <> 1 THEN
    RAISE_APPLICATION_ERROR(-20001, 'A soma dos percentuais deve ser 100%');
  END IF;

  FOR I IN 1 .. PERCENTUAIS.COUNT
  LOOP
    IF I < PERCENTUAIS.COUNT THEN
      VALOR_RATEADO := ROUND(VALOR_NOTA * PERCENTUAIS(I), 2);
    ELSE
      VALOR_RATEADO := VALOR_NOTA - SOMA_RATEADA;
    END IF;
    SOMA_RATEADA := SOMA_RATEADA + VALOR_RATEADO;
    PIPE ROW(VALOR_RATEADO);
  END LOOP;
END;
