CREATE OR REPLACE FUNCTION FUNC_RATEAR_VALOR_POR_CC(
                                                    
                                                    VALOR_NOTA  IN NUMBER,
                                                    PERCENTUAIS IN T_PERCENTUAIS_CC) RETURN T_PERCENTUAIS_CC
  PIPELINED IS
  VALOR_RATEADO NUMBER;
  SOMA_RATEADA  NUMBER := 0;

BEGIN

  FOR I IN 1 .. PERCENTUAIS.COUNT
  LOOP
    IF I < PERCENTUAIS.COUNT THEN
      VALOR_RATEADO := ROUND(VALOR_NOTA * PERCENTUAIS(I), 2);
    ELSE
      VALOR_RATEADO := VALOR_NOTA - SOMA_RATEADA;
    END IF;
    SOMA_RATEADA := SOMA_RATEADA + VALOR_RATEADO;
    PIPE ROW(VALOR_RATEADO);
  END LOOP;
END;
