CREATE OR ALTER PROCEDURE SP_RETORNA_CLIENTE
    @CODCLIENTE INT
AS
BEGIN    
    IF EXISTS (SELECT 1 FROM CLIENTE WHERE CODCLIENTE = @CODCLIENTE)
	SELECT FORMAT(DTUPDATE, 'yyyy-MM-dd HH:mm:ss') DTUPDATE FROM CLIENTE WHERE CODCLIENTE = @CODCLIENTE
END