CREATE OR REPLACE PROCEDURE PRC_SINC_PARAMETROS_GLOBAL(
    pPARAMETRO IN VARCHAR2,
    pVALOR     IN VARCHAR2,
    pDESCRICAO IN VARCHAR2
) AS

BEGIN
    -- Tenta atualizar o registro existente
    UPDATE BI_SINC_PARAMETROS_GLOBAL
       SET VALOR = pVALOR,
           DESCRICAO = pDESCRICAO,
           DT_UPDATE = SYSDATE
     WHERE PARAMETRO = pPARAMETRO;

    -- Se nenhum registro foi atualizado, insere um novo
    IF SQL%ROWCOUNT = 0 THEN
        INSERT INTO BI_SINC_PARAMETROS_GLOBAL (PARAMETRO, VALOR, DESCRICAO, DT_UPDATE)
        VALUES (pPARAMETRO, pVALOR, pDESCRICAO, SYSDATE);
    END IF;

COMMIT;

END PRC_SINC_PARAMETROS_GLOBAL;


