CREATE OR REPLACE PROCEDURE PRC_SINC_TABELAS_DW AS
  v_table_exists NUMBER;
	v_index_exists NUMBER;
BEGIN
  ----BI_SINC_FILIAL
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_FILIAL';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_FILIAL
  (
     CODFILIAL  VARCHAR2(2),
     EMPRESA    VARCHAR2(150),
     FILIAL     VARCHAR2(25),
     ORDEM      NUMBER(2),
     CODEMPRESA VARCHAR2(2), 
     DT_UPDATE  DATE,
     CONSTRAINT PK_CODFILIAL PRIMARY KEY (CODFILIAL)
  )';
  END IF;

  ----BI_SINC_PRODUTO
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_PRODUTO';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_PRODUTO
  (
     CODPROD         NUMBER(6),
     PRODUTO         VARCHAR2(40),
     CODPRODMASTER   NUMBER(6),
     PRODUTOMASTER   VARCHAR2(40),
     CODDEPTO        NUMBER(6),
     DEPARTAMENTO    VARCHAR2(25),
     CODSECAO        NUMBER(6),
     SECAO           VARCHAR2(40),
     CODCATEGORIA    NUMBER(6),
     CATEGORIA       VARCHAR2(40),
     CODLINHA        NUMBER(6),
     LINHA           VARCHAR2(40),
     PRODUTOFILHO    VARCHAR2(1),
     CODFORNEC       NUMBER(6),
     CODMARCA        NUMBER(8),
     MARCA           VARCHAR2(40),
     TIPOCOMISSAO    VARCHAR2(40),
     CODFAB          VARCHAR2(30),
     CODBARRAS       NUMBER(20),
     CODBARRASMASTER NUMBER(14),
     PESO            NUMBER(12, 6),
     LARGURA         NUMBER(20, 6),
     ALTURA          NUMBER(20, 6),
     COMPRIMENTO     NUMBER(20, 6),
     VOLUME          NUMBER(20, 8),
     QTCXMASTER      NUMBER(8, 2),
     IMPORTADO       VARCHAR2(1),
     REVENDA         VARCHAR2(1),
     NCM             VARCHAR2(15),
     NCMEX           VARCHAR2(20),
     TIPOMERCADORIA  VARCHAR2(20),
     FORALINHA       VARCHAR2(1),
     CERTIFICACAO    VARCHAR2(200),
     DT_UPDATE       DATE,
     CONSTRAINT PK_CODPROD PRIMARY KEY (CODPROD)
  )';
  END IF;

  ----BI_SINC_FORNECEDOR
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_FORNECEDOR';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_FORNECEDOR
  (
     CODFORNEC      NUMBER(6),
     FORNECEDOR     VARCHAR2(60),
     CODFORNECPRINC NUMBER(6),
     FORNECPRINC    VARCHAR2(70),
     CNPJ           VARCHAR2(18),
     TIPO           VARCHAR2(1),
     DT_UPDATE      DATE,
     CONSTRAINT PK_CODFORNEC PRIMARY KEY (CODFORNEC)
  )';
  END IF;

  ----JFAREACOMERCIAL
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'JFAREACOMERCIAL';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JFAREACOMERCIAL
  (
     CODAREA       NUMBER(2),
     AREACOMERCIAL VARCHAR2(40),
     CONSTRAINT PK_CODAREA PRIMARY KEY (CODAREA)
  )';
  END IF;

  ----BI_SINC_VENDEDOR
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_VENDEDOR';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_VENDEDOR
  (
     CODUSUR       NUMBER(6),
     NOMEORIGINAL  VARCHAR2(40),
     VENDEDOR      VARCHAR2(40),
     CARGO         VARCHAR2(20),
     CODFILIAL     VARCHAR2(2),
     BLOQUEIO      VARCHAR2(1),
     CODSUPERVISOR NUMBER(4),
     SUPERVISOR    VARCHAR2(40),
     CODGERENTE    NUMBER(4),
     GERENTE       VARCHAR2(40),
     CODAREA       NUMBER(2),
     AREACOMERCIAL VARCHAR2(40),
     DT_UPDATE     DATE,
     CONSTRAINT PK_CODUSUR PRIMARY KEY (CODUSUR)
  )';
  END IF;

  ----BI_SINC_COMPRADOR
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_COMPRADOR';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_COMPRADOR
  (
     MATRICULA NUMBER(6),
     COMPRADOR VARCHAR2(15),
     DT_UPDATE DATE,
     CONSTRAINT PK_MATRICULA PRIMARY KEY (MATRICULA)
  )';
  END IF;

  ----BI_SINC_CLIENTE
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_CLIENTE';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_CLIENTE
  (
     CODCLI             NUMBER(6),
     CLIENTE            VARCHAR2(60),
     CODCLIREDE         VARCHAR2(8),
     CLIENTEREDE        VARCHAR2(80),
     CNPJ               VARCHAR2(18),
     CEP                VARCHAR2(9),
     UF                 VARCHAR2(2),
     CODFILIALJCCLUB    VARCHAR2(2),
     CODUSUR            NUMBER(4),
     CODPRACA           NUMBER(4),
     PRACA              VARCHAR2(25),
     CODATIVIDADE       NUMBER(6),
     RAMOATIVIDADE      VARCHAR2(40),
     BLOQUEIODEFINITIVO VARCHAR2(1),
     BLOQUEIOATUAL      VARCHAR2(1),
     LIMITECREDITO      NUMBER(12, 2),
     DTCADASTRO         DATE,
     DT_UPDATE          DATE,
     CONSTRAINT PK_CODCLI PRIMARY KEY (CODCLI)
  )';
  END IF;

  ----BI_SINC_ESTOQUE
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_ESTOQUE';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_ESTOQUE
  (
     CODFILIAL           VARCHAR2(2),
     CODPROD             NUMBER(6),
     QTCONTABIL          NUMBER(22, 8),
     QTGERENCIAL         NUMBER(22, 8),
     QTBLOQUEADA         NUMBER(20, 6),
     QTPENDENTE          NUMBER(16, 3),
     QTRESERVADA         NUMBER(22, 6),
     QTAVARIADA          NUMBER(20, 6),
     QTDISPONIVEL        NUMBER(20, 6),
     QTFRENTELOJA        NUMBER(22, 6),
     QTDEPOSITO          NUMBER(22, 6),
     VALORULTENT         NUMBER(18, 6),
     CUSTOREPOSICAO      NUMBER(18, 6),
     CUSTOFINANCEIRO     NUMBER(18, 6),
     CUSTOCONTABIL       NUMBER(18, 6),
     VLESTOQUECONTABIL   NUMBER(18, 6),
     VLESTOQUEFINANCEIRO NUMBER(18, 6),
     VLESTOQUEGERENCIAL  NUMBER(18, 6),
     VLESTOQUELOJA       NUMBER(18, 6),
     VLESTOQUEDEPOSITO   NUMBER(18, 6),
     VLESTOQUEDISPONIVEL NUMBER(18, 6),
     VLESTOQUEAVARIADO   NUMBER(18, 6),
     CODBLOQUEIO         NUMBER(4),
     MOTIVOBLOQUEIO      VARCHAR2(30),
     DT_UPDATE           DATE,
     CONSTRAINT PK_CODFILIAL_CODPROD PRIMARY KEY (CODFILIAL, CODPROD)
  )';
  END IF;

  ----BI_SINC_PRECO_COMPRA
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_PRECO_COMPRA';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_PRECO_COMPRA
  (
     CODFILIAL       VARCHAR2(2),
     CODPROD         NUMBER(6),
     PTABELA         NUMBER(18, 6),
     PCOMPRA         NUMBER(18, 6),
     VLIPI           NUMBER(18, 6),
     VLST            NUMBER(18, 6),
     PBRUTO          NUMBER(18, 6),
     VLCREDICMS      NUMBER(18, 6),
     VLPIS           NUMBER(18, 6),
     VLCOFINS        NUMBER(18, 6),
     CUSTOLIQ        NUMBER(18, 6),
     BASEICMS        NUMBER(18, 6),
     BASEPISCOFINS   NUMBER(18, 6),
     PERCPIS         NUMBER(18, 6),
     PERCCOFINS      NUMBER(18, 6),
     PERCIPI         NUMBER(18, 6),
     PERCICMS        NUMBER(18, 6),
     PERCICMSRED     NUMBER(18, 6),
     PERCCREDICMS    NUMBER(18, 6),
     PERCIVA         NUMBER(18, 6),
     PERCALIQEXT     NUMBER(18, 6),
     PERCALIQINT     NUMBER(18, 6),
     PERCALIQEXTGUIA NUMBER(18, 6),
     REDBASEALIQEXT  NUMBER(18, 6),
     PERCALIQSTRED   NUMBER(18, 6),
     DT_UPDATE       DATE,
     CONSTRAINT PK_PRECO_COMPRA PRIMARY KEY (CODFILIAL, CODPROD)
  )';
  END IF;

  ----BI_SINC_MOV_PRODUTO
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_MOV_PRODUTO';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_MOV_PRODUTO
  (
     NUMTRANSITEM      NUMBER(18),
     MOVIMENTO         VARCHAR2(1),
     TIPOMOV           VARCHAR2(60),
     CODFILIAL         VARCHAR2(2),
     NUMTRANSACAO      NUMBER(10),
     TEMVENDAORIG      VARCHAR2(1),
     CODCOB            VARCHAR2(4),
     PARCELAS          NUMBER(4),
     PRAZO             NUMBER(6),
     CODUSUR           NUMBER(4),
     CODFORNEC         NUMBER(8),
     CODCLI            NUMBER(8),
     NUMNOTA           NUMBER(10),
     DATA              DATE,
     CODPROD           NUMBER(6),
     QT                NUMBER(20, 6),
     CUSTOFINANCEIRO   NUMBER(18, 6),
     CUSTOREPOSICAO    NUMBER(18, 6),
     CUSTOCONTABIL     NUMBER(18, 6),
     VLCONTABIL        NUMBER(18, 6),
     PUNIT             NUMBER(18, 6),
     PTABELA           NUMBER(18, 6),
     VLPRODUTO         NUMBER(18, 6),
     VLDESCONTO        NUMBER(18, 6),
     CST_ICMS          VARCHAR2(3),
     CFOP              NUMBER(8),
     VLBASEICMS        NUMBER(18, 6),
     PERCICMS          NUMBER(12, 4),
     VLICMS            NUMBER(18, 6),
     VLICMSBENEFICIO   NUMBER(18, 6),
     VLST              NUMBER(18, 6),
     VLSTGUIA          NUMBER(18, 6),
     PERCIPI           NUMBER(12, 4),
     VLIPI             NUMBER(18, 6),
     CST_PISCOFINS     VARCHAR2(3),
     VLBASEPISCOFINS   NUMBER(18, 6),
     PERCPIS           NUMBER(12, 4),
     PERCCOFINS        NUMBER(12, 4),
     VLPIS             NUMBER(18, 6),
     VLCOFINS          NUMBER(18, 6),
     VLFRETE           NUMBER(18, 6),
     VLOUTRASDESP      NUMBER(18, 6),
     VLICMSDIFAL       NUMBER(18, 6),
     VLCMVGERENCIAL    NUMBER(18, 6),
     VLCMVCONTABIL     NUMBER(18, 6),
     DTCANCEL          DATE,
     DT_UPDATE         DATE,
     CONSTRAINT PK_NUMTRANSITEM PRIMARY KEY (NUMTRANSITEM)
  ) ';
  END IF;
	
	----INDICES BI_SINC_MOV_PRODUTO
	SELECT COUNT(*)
    INTO v_index_exists
    FROM user_indexes
   WHERE table_name = 'BI_SINC_MOV_PRODUTO'
   AND index_name = 'IDX_TIPOMOV';
  IF v_index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_TIPOMOV ON BI_SINC_MOV_PRODUTO (TIPOMOV)';
  END IF;
	
	SELECT COUNT(*)
    INTO v_index_exists
    FROM user_indexes
   WHERE table_name = 'BI_SINC_MOV_PRODUTO'
   AND index_name = 'IDX_01';
  IF v_index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_01 ON BI_SINC_MOV_PRODUTO (CODFILIAL, CODUSUR)';
  END IF;

  ----BI_SINC_PRECO_VENDA
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_PRECO_VENDA';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_PRECO_VENDA
  (
     CODPROD     NUMBER(6),
     NUMREGIAO   NUMBER(4),
     PRECOVENDA  NUMBER(18, 6),
     MARGEMIDEAL NUMBER(6, 2),
     DT_UPDATE   DATE,
     CONSTRAINT PK_BI_SINC_PRECO_VENDA PRIMARY KEY (CODPROD, NUMREGIAO)
  ) ';
  END IF;

  ----BI_SINC_PRECO_VENDA_PROMOCIONAL
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_PRECO_VENDA_PROMOCIONAL';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_PRECO_VENDA_PROMOCIONAL
  (
     CODPRECOPROM     NUMBER(10),
     CODFILIAL        VARCHAR2(2),
     CODPROD          NUMBER(6),
     NUMREGIAO        NUMBER(4),
     CODATIVIDADE     NUMBER(6),
     PRECOPROMOCIONAL NUMBER(18, 6),
     DTINICIOPROMOCAO DATE,
     DTFIMPROMOCAO    DATE,
     ATIVO            VARCHAR(2),
     DT_UPDATE        DATE,
     CONSTRAINT PK_BI_SINC_PRECO_VENDA_PROMO PRIMARY KEY (CODPRECOPROM)
  ) ';
  END IF;

  ----BI_SINC_PEDIDO_COMPRA
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_PEDIDO_COMPRA';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_PEDIDO_COMPRA
  (
     CODFILIAL    VARCHAR2(2),
     DATA         DATE,
     CODFORNEC    NUMBER(6),
     CODCOMPRADOR NUMBER(8),
     TIPO         VARCHAR2(20),
     NUMPED       NUMBER(10),
     NUMSEQ       NUMBER(6),
     CODPROD      NUMBER(6),
     PRECOCOMPRA  NUMBER(18, 6),
     QTPEDIDA     NUMBER(20, 6),
     QTENTREGUE   NUMBER(20, 6),
     QTSALDO      NUMBER(20, 6),
     VLPEDIDO     NUMBER(18, 6),
     VLENTREGUE   NUMBER(18, 6),
     VLSALDO      NUMBER(18, 6),
     DT_UPDATE    DATE,
     CONSTRAINT PK_BI_SINC_PEDIDO_COMPRA PRIMARY KEY (NUMPED, NUMSEQ, CODPROD )
  )';
  END IF;

  ----BI_SINC_LANC_PAGAR
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_LANC_PAGAR';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_LANC_PAGAR
  (
     RECNUM         NUMBER(8),
     CODFILIAL      VARCHAR2(2),
     DTCOMPETENCIA  DATE,
     DTVENCIMENTO   DATE,
     DTPAGAMENTO    DATE,
     DTCONTABIL     DATE,
     TIPO           VARCHAR2(25),
     VALOR          NUMBER(14, 2),
     VLJUROS        NUMBER(14, 2),
     VLDESCONTO     NUMBER(14, 2),
     VALORAPAGAR    NUMBER(14, 2),
     CODBANCO       NUMBER(4),
     CODCONTA       NUMBER(10),
     CODFORNEC      NUMBER(8),
     TIPOPARCEIRO   VARCHAR2(1),
     NUMTRANS       NUMBER(10),
     NUMNOTA        NUMBER(10),
     DUPLICATA      VARCHAR2(1),
     HISTORICO      VARCHAR2(200),
     OBSERVACAO     VARCHAR2(200),
     RECNUMPRINC    NUMBER(8),
     CODROTINABAIXA NUMBER(4),
     DT_UPDATE      DATE,
     CONSTRAINT PK_BI_SINC_LANC_PAGAR PRIMARY KEY (RECNUM)
  ) ';
  END IF;

  ----BI_SINC_REGIAO
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_REGIAO';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_REGIAO
  (
     NUMREGIAO NUMBER(4),
     REGIAO    VARCHAR2(40),
     DT_UPDATE DATE,
     CONSTRAINT PK_BI_SINC_REGIAO PRIMARY KEY (NUMREGIAO)
  ) ';
  END IF;

  ----BI_SINC_CALENDARIO
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_CALENDARIO';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_CALENDARIO
  (
    DATA                    DATE,
    DIA                     NUMBER(2),
    ANO                     NUMBER(4),
    NUM_MES                 NUMBER(2),
    NOME_MES                VARCHAR2(12),
    NOME_MES_ABREV          VARCHAR2(3),
    NUM_MES_ANO             NUMBER(6),
    NUM_MES_ANO_SEQ         NUMBER(6),
    MES_ANO                 VARCHAR2(8),
    NUM_DIA_ANO             NUMBER(3),
    NUM_TRIMESTRE           NUMBER(1),
    NOME_TRIMESTRE          VARCHAR2(12),
    NOME_TRIMESTRE_ABREV    VARCHAR2(6),
    NUM_TRIMESTRE_ANO       NUMBER(6),
    NOME_TRIMESTRE_ANO      VARCHAR2(12),
    NUM_TRIMESTRE_JC        NUMBER(1),
    NOME_TRIMESTRE_JC       VARCHAR2(12),
    NOME_TRIMESTRE_ABREV_JC VARCHAR2(6),
    NUM_TRIMESTRE_ANO_JC    NUMBER(6),
    NOME_TRIMESTRE_ANO_JC   VARCHAR2(12),
    NUM_SEMANA_MES          NUMBER(1),
    NOME_SEMANA_MES         VARCHAR2(10),
    NUM_SEMANA_ANO          NUMBER(2),
    NOME_SEMANA_ANO         VARCHAR2(12),
    NUM_DIA_SEMANA          NUMBER(1),
    NOME_DIA_SEMANA         VARCHAR2(14),
    NOME_DIA_SEMANA_ABREV   VARCHAR2(3),
    CALCULO_MES_ATUAL       NUMBER(4),
    CALCULO_TRIMESTRE_ATUAL NUMBER(4),
    CALCULO_ANO_ATUAL       NUMBER(4),
    DIA_UTIL_FINANCEIRO     DATE,
    DT_UPDATE               DATE,
    CONSTRAINT PK_BI_SINC_CALENDARIO PRIMARY KEY (DATA)
  )';
  END IF;

  ----BI_SINC_TABELAS
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_TABELAS';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_TABELAS
  (
     TABELA         VARCHAR2(128),
     QTREGISTROS    NUMBER,
     MAIOR_DTUPDATE DATE,
     LAST_REFRESH   DATE,
     DT_UPDATE      DATE,
     CONSTRAINT PK_BI_SINC_TABELAS PRIMARY KEY (TABELA)
  ) ';
  END IF;

  ----BI_SINC_META_VENDEDOR
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_META_VENDEDOR';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_META_VENDEDOR
  (
     DATA      DATE,
     CODUSUR   NUMBER(4),
     VLMETA    NUMBER(18, 6),
     DT_UPDATE DATE,
     CONSTRAINT PK_META_VENDEDOR PRIMARY KEY (DATA, CODUSUR)
  ) ';
  END IF;

  ----BI_SINC_META_CLIENTE
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_META_CLIENTE';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_META_CLIENTE
  (
     DATA       DATE,
     CODCLIREDE VARCHAR2(10),
     VLMETA     NUMBER(18, 6),
     DT_UPDATE  DATE,
     CONSTRAINT PK_META_CLIENTE PRIMARY KEY (DATA, CODCLIREDE)
  ) ';
  END IF;

  ----BI_SINC_PEDIDO_VENDA
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_PEDIDO_VENDA';
  IF v_table_exists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_PEDIDO_VENDA
  (
     CODFILIAL         VARCHAR2(2),
     CODFILIALRETIRA   VARCHAR2(2),
     DATA              DATE,
     DATALIMITE        DATE,
     NUMPED            NUMBER(10),
     TIPOVENDA         NUMBER(5),
     NUMSEQ            NUMBER(6),
     CODCLI            NUMBER(6),
     CODPROD           NUMBER(6),
     QT                NUMBER(20, 6),
     PVENDA            NUMBER(18, 6),
     VLPRODUTO         NUMBER(18, 6),
     VLPEDIDO          NUMBER(18, 6),
     CODUSUR           NUMBER(4),
     POSICAO           VARCHAR2(2),
     TIPOBLOQUEIO      VARCHAR2(1),
     MOTIVOBLOQUEIO    VARCHAR2(200),
     OBSPEDIDO         VARCHAR2(25),
     CODMOTIVOPENDENTE NUMBER(2),
     DT_UPDATE         DATE,
     CONSTRAINT PK_PEDIDO_VENDA PRIMARY KEY (NUMPED, CODPROD, NUMSEQ)
  )  ';
  END IF;
  
    ----BI_SINC_PLANO_CONTAS_JC
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_PLANO_CONTAS_JC';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_PLANO_CONTAS_JC
  (
     CODCLASSIFICA VARCHAR2(12),
     CONTA         VARCHAR2(60),
     NIVEL         NUMBER(1),
     TIPOCONTA     NUMBER(1),
     CODGERENCIAL  NUMBER(4),
     CODCONTABIL   NUMBER(5),
     CODBALANCO    NUMBER(1),
     CODDRE        NUMBER(2),
     CODEBTIDA     NUMBER(1),
     CONTAN1       VARCHAR2(30),
     CONTAN2       VARCHAR2(40),
     CONTAN3       VARCHAR2(60),
     CONTAN4       VARCHAR2(80),
     CONTAN5       VARCHAR2(80),
     DT_UPDATE     DATE,
     CONSTRAINT PK_PLANO_CONTAS_JC PRIMARY KEY (CODCLASSIFICA)
  ) ';
  END IF;

    ----BI_SINC_DRE_JC
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_DRE_JC';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_DRE_JC
  (
     CODDRE      NUMBER(2),
     SUBCONTADRE VARCHAR2(60),
     SUBTOTAL    NUMBER(1),
     CONTADRE    VARCHAR2(60),
     GRUPODRE    VARCHAR2(60),
     DT_UPDATE   DATE,
     CONSTRAINT PK_DRE_JC PRIMARY KEY (CODDRE)
  ) ';
  END IF;
  
    ----BI_SINC_PARAMETROS_GLOBAL
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_PARAMETROS_GLOBAL';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_PARAMETROS_GLOBAL
  (
     PARAMETRO VARCHAR2(60),
     VALOR     VARCHAR2(24),
     DESCRICAO VARCHAR2(128),
     DT_UPDATE DATE,
     CONSTRAINT PK_PARAMETROS_GLOBAL PRIMARY KEY (PARAMETRO)
  ) ';
  END IF;

    ----BI_SINC_CENTRO_CUSTO
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_CENTRO_CUSTO';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_CENTRO_CUSTO
  (
     CODCENTROCUSTO VARCHAR2(4),
     CENTROCUSTO    VARCHAR2(32),
     DT_UPDATE      DATE,
     CONSTRAINT PK_CENTRO_CUSTO PRIMARY KEY (CODCENTROCUSTO)
  ) ';
  END IF;
	
	  ----BI_SINC_FORNECEDOR_CONTABIL
  SELECT COUNT(*)
    INTO v_table_exists
    FROM user_tables
   WHERE table_name = 'BI_SINC_FORNECEDOR_CONTA';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BI_SINC_FORNECEDOR_CONTA
  (
     CODEMPRESA    VARCHAR2(2),
     CODFORNEC     NUMBER(6),
     CODCONTABIL   NUMBER(5),
     CODCLASSIFICA VARCHAR2(12),
     DT_UPDATE      DATE,
     CONSTRAINT PK_FORNECEDOR_CONTA PRIMARY KEY (CODEMPRESA, CODFORNEC, CODCONTABIL)
  )';
  END IF;

END;
