CREATE OR REPLACE VIEW VIEW_BI_SINC_DESPESA_CONTABIL AS

    WITH LANCAMENTO AS
     (SELECT *
        FROM (SELECT L.RECNUM,
                     L.ANO_COMPETENCIA,
                     L.CODFORNEC,
                     L.NUMNOTA,
                     ROW_NUMBER() OVER (PARTITION BY ANO_COMPETENCIA, CODFORNEC, NUMNOTA ORDER BY RECNUM) AS RN
                FROM BI_SINC_LANC_PAGAR_BASE L
                JOIN BI_SINC_PLANO_CONTAS_JC P ON P.CODGERENCIAL = L.CODCONTA
               WHERE L.TIPOPARCEIRO = 'F'
                 AND L.NUMNOTA > 0
                 AND P.CODDRE IS NOT NULL)
       WHERE RN = 1),
    
    FRETES AS
     (SELECT E.NUMTRANSENT,
             V.CODSUPERVISOR
        FROM BI_SINC_DESPESA_FISCAL E
        JOIN PCCONHECIMENTOFRETEI F ON F.NUMTRANSCONHEC = E.NUMTRANSENT
        JOIN PCNFSAID S ON S.CHAVENFE = F.CHAVENFE
        LEFT JOIN BI_SINC_VENDEDOR V ON V.CODUSUR = S.CODUSUR
       WHERE E.ESPECIE = 'CT'
       GROUP BY E.NUMTRANSENT,
                V.CODSUPERVISOR)
    
    SELECT E.CODEMPRESA,
           E.CODFILIAL,
           E.DATA,
           E.NUMTRANSENT,
           F.CODSUPERVISOR,
           E.NUMNOTA,
           E.CODCONTA,
           E.CODFORNEC,
           E.FORNECEDOR,
           E.ESPECIE,
           E.CFOP,
           NVL(E.VALOR, 0) VALOR,
           NVL(ROUND((E.VALOR * NVL(C.PERCRATEIO, 100) / 100), 2), NVL(E.VALOR, 0)) VLRATEIO,
           NVL(ROUND((E.VLICMS * NVL(C.PERCRATEIO, 100) / 100), 6), NVL(E.VLICMS, 0)) VLICMS,
           NVL(ROUND((E.VLPIS * NVL(C.PERCRATEIO, 100) / 100), 6), NVL(E.VLPIS, 0)) VLPIS,
           NVL(ROUND((E.VLCOFINS * NVL(C.PERCRATEIO, 100) / 100), 6), NVL(E.VLCOFINS, 0)) VLCOFINS,
           NVL(ROUND((E.VLDIFAL * NVL(C.PERCRATEIO, 100) / 100), 2), NVL(E.VLDIFAL, 0)) VLDIFAL,
           NVL(L.RECNUM, 0) RECNUM,
           NVL(C.VLIMPOSTO, 0) VLIMPOSTO,
           NVL(C.CODCC, '0') CODCC,
           NVL(ROUND(C.PERCRATEIO, 2), 0) PERCRATEIO
      FROM BI_SINC_DESPESA_FISCAL E
      LEFT JOIN FRETES F ON F.NUMTRANSENT = E.NUMTRANSENT
      LEFT JOIN LANCAMENTO L ON L.NUMNOTA = E.NUMNOTA
                            AND L.CODFORNEC = E.CODFORNEC
                            AND L.ANO_COMPETENCIA = E.ANO
      LEFT JOIN BI_SINC_LANC_PAGAR_BASE C ON C.RECNUM = L.RECNUM
