CREATE OR ALTER PROCEDURE SP_RETORNA_FILIAL
    @CODFILIAL NCHAR(2)
AS
BEGIN    

    IF EXISTS (SELECT 1 FROM FILIAL WHERE CODFILIAL = @CODFILIAL)
	SELECT FORMAT(DTUPDATE, 'yyyy-MM-dd HH:mm:ss') DTUPDATE FROM FILIAL WHERE CODFILIAL = @CODFILIAL
END