CREATE OR REPLACE PROCEDURE PRC_RETORNO_FILIAL
(
  pCODFILIAL      IN PCFILIAL.CODIGO%TYPE,
  pDTUPDATE IN TIMESTAMP
) AS
BEGIN
  UPDATE BI_SINC_FILIAL
     SET DT_SINC = pDTUPDATE
   WHERE CODFILIAL = pCODFILIAL;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Nenhum registro encontrado para a marca ' ||
                         TO_CHAR(pCODFILIAL));
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro inesperado:' || SQLERRM);
  
END;
