CREATE OR ALTER PROCEDURE SP_CARREGA_FILIAL
	@CODFILIAL CHAR(3),
	@EMPRESA NVARCHAR(150),
	@FILIAL NVARCHAR(25)
AS
BEGIN    
	----Faz a transformação das informações
       DECLARE @ORDEM SMALLINT
       SET @ORDEM = CONVERT(SMALLINT, @CODFILIAL)
	   SET @EMPRESA  = CASE WHEN @EMPRESA IS NULL THEN 'JC BROTHERS' ELSE @EMPRESA END
       SET @FILIAL  =  CASE WHEN @FILIAL IS NULL THEN  'JC BROTHERS' ELSE @FILIAL END
        
    ----faz o merge das informações
        IF EXISTS (SELECT 1 FROM FILIAL WHERE [Cod.Filial] = @CODFILIAL)
			BEGIN
			UPDATE FILIAL SET EMPRESA = @EMPRESA, FILIAL = @FILIAL WHERE [Cod.Filial] = @CODFILIAL
		END
    	ELSE
			BEGIN
			INSERT INTO FILIAL ([Cod.Filial], Empresa, Filial, Ordem)
			VALUES (@CODFILIAL, @EMPRESA, @FILIAL, @ORDEM)
	END
END