CREATE OR ALTER PROCEDURE SP_CARREGA_FILIAL
	@CODFILIAL NCHAR(2),
	@EMPRESA NVARCHAR(150),
	@FILIAL NVARCHAR(25)
AS
BEGIN    
----Faz a transformação das informações
	DECLARE @ORDEM SMALLINT = CONVERT(SMALLINT, @CODFILIAL)
	DECLARE @DTUPDATE DATETIME = DATEADD(hour, -3, GETUTCDATE())

	SET @EMPRESA  = CASE WHEN @EMPRESA = 'NULL' THEN 'JC BROTHERS' ELSE @EMPRESA END
	SET @FILIAL  =  CASE WHEN @FILIAL = 'NULL' THEN  'JC BROTHERS' ELSE @FILIAL END
	
----faz o merge das informações
	IF EXISTS (SELECT 1 FROM FILIAL WHERE [CodFilial] = @CODFILIAL)
		BEGIN
		UPDATE FILIAL SET EMPRESA = @EMPRESA, FILIAL = @FILIAL, DTUPDATE = @DTUPDATE WHERE [CodFilial] = @CODFILIAL
	END
	ELSE
	BEGIN
		INSERT INTO FILIAL ([CodFilial], Empresa, Filial, Ordem, DtUpdate)
		VALUES (@CODFILIAL, @EMPRESA, @FILIAL, @ORDEM, @DTUPDATE)
	END
END