CREATE OR ALTER PROCEDURE SP_INGEST_STGFILIAL
	@CODFILIAL NCHAR(2),
	@EMPRESA NVARCHAR(150),
	@FILIAL NVARCHAR(25)
AS
BEGIN
	IF NOT EXISTS (SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'STGFILIAL')
    BEGIN
		SET ANSI_NULLS ON

		SET QUOTED_IDENTIFIER ON

		CREATE TABLE [dbo].[STGFILIAL]
		(
			[CODFILIAL] [nchar](2) NOT NULL,
			[EMPRESA] [nvarchar](150) NULL,
			[FILIAL] [nvarchar](25) NULL
		) ON [PRIMARY]

		SET ANSI_PADDING ON

		ALTER TABLE [dbo].[STGFILIAL] ADD  CONSTRAINT [PK_STGFILIAL] PRIMARY KEY CLUSTERED 
		(
			[CODFILIAL] ASC
		)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

		CREATE UNIQUE NONCLUSTERED INDEX [Index_STGFILIAL_1] ON [dbo].[STGFILIAL]
		(
			[CODFILIAL] ASC
		)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	END

	BEGIN
		IF EXISTS (SELECT 1
		FROM STGFILIAL
		WHERE CODFILIAL = @CODFILIAL)
			BEGIN
			UPDATE STGFILIAL SET EMPRESA = @EMPRESA, FILIAL = @FILIAL WHERE CODFILIAL = @CODFILIAL
		END
    	ELSE
			BEGIN
			INSERT INTO STGFILIAL
				(CODFILIAL, EMPRESA, FILIAL)
			VALUES
				(@CODFILIAL, @EMPRESA, @FILIAL)
		END
	END
END